### PR TITLE
New Footer was added following design on zeplin.

### LINKED ISSUE #9: Add footer of the site
Make sure our footer is stick to the bottom, so regardless the content it will be displayed at the bottom of the screen.

desktop_home_v2_-_hash_labs_v5_-_zeplin

_check design at zeplin to look for mobile layout_

### PR DESCRIPTION
**Pull request by TheMightyPenguin**
# Context
Added the new Footer, by following the design on zeplin, it was implemented for both desktop and mobile. This PR closes #9

* Added new include, section-footer.html
* Added new added footer component styles
* Refactor for mobile styles

## Links
* [Zeplin desktop design](https://app.zeplin.io/project.html#pid=5888b73ba8de3a354ef67567&sid=588f6811cb4fd20443ab9447)
* [Zeplin mobile design](https://app.zeplin.io/project.html#pid=5888b73ba8de3a354ef67567&sid=58b86d91c50cf643a18ef7b2)

## Media
footer
sticky footer

### CODE REVIEW

**Comment by duranmla** [comment]
The footer should be sticky if there is no content within the page the footer will remain at the bottom. make sure to add a screenshot with a proof of that too, I will close this PR until we get what we want

**Comment by TheMightyPenguin** [comment]
I need to open this issue again!

**Comment by TheMightyPenguin** [comment]
Now with Sticky Footer!

**Comment by TheMightyPenguin** [comment]
Added sticky footer image!

**Pull request closed without merging**
