### PR TITLE
SEO Optimizations and sitemap

### PR DESCRIPTION
**Pull request by carlows**
# Context

This PR adds:

- Jekyll SEO tag to add the required meta tags for search engines.
- All images now have alt tags.
- Jekyll sitemap to generate a sitemap.xml on each build.
- Small fix to be able to include twitter small image card.

## Links

* https://dev.twitter.com/cards/types/summary
* https://developers.facebook.com/tools/debug/sharing/
* https://cards-dev.twitter.com/validator
* https://github.com/jekyll/jekyll-seo-tag/issues/84
* https://developers.facebook.com/docs/sharing/best-practices

### Twitter card (https://cards-dev.twitter.com/validator/)

image

### Facebook card (https://developers.facebook.com/tools/debug/sharing/?q=labcoat-seo-test.firebaseapp.com)

image

### Google results preview (https://seositecheckup.com/seo-audit/google-search-results-preview/labcoat-seo-test.firebaseapp.com)

image

### Telegram preview

image

### Included metadata

image

### CODE REVIEW

**Review by TheMightyPenguin — DISMISSED** [review]
LGTM, just add the missing images and merge :+1:

**Review by duranmla — DISMISSED** [review]
Hold until real images

**Review by TheMightyPenguin — DISMISSED** [review]
LGTM, and a 🌮  for telegram

**Review by TheMightyPenguin — APPROVED** [review]
LGTM, thanks for adding to the faq!

**Pull request merged**
